<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Text-Dashboard</name>
   <tag></tag>
   <elementGuidId>fe1bf088-56e6-4e73-be26-9e69f202a3da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h1[(text() = 'Dashboard' or . = 'Dashboard')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>6d50725a-69ad-4d15-bc9c-2c313a31ffdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>28baffe8-9877-4758-8fa8-4012bc2e5ab0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
